from mynetworks.neuralnetwork import NeuralNetwork
from mynetworks.hardlynormalizedneuralnetwork import HardlyNormalizedNeuralNetwork
from mynetworks.softlynormalizedneuralnetwork import SoftlyNormalizedNeuralNetwork
